---
name: tmp
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  tmp:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up cgroup delegation
        run: |
          sudo mkdir -p /etc/systemd/system/user@.service.d
          cat <<EOF | sudo tee /etc/systemd/system/user@.service.d/delegate.conf
          [Service]
          Delegate=cpu cpuset io memory pids
          EOF
          sudo systemctl daemon-reload
          whoami
      - name: Set up rootless docker
        run: |
          cat /sys/fs/cgroup/user.slice/user-$(id -u).slice/user@$(id -u).service/cgroup.controllers
          sudo apt-get remove moby-engine-*
          curl https://get.docker.com | sudo sh
          dockerd-rootless-setuptool.sh install -f
          docker context use rootless
          docker info
